version: "3.7"
services:
  graphql-app:
    build:
      context: .
      args:
        - JAR_FILE=./target/games-0.0.1-SNAPSHOT.jar
        - CONFIG_FILE_NAME=application-within-docker.yaml
    restart: always
    container_name: graphql-app
    ports:
      - 8080:8080
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin # obviously not the best
      POSTGRES_DB: games
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  # totally optional
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8081:8080

volumes:
  postgres:
